import { delay } from '@/utils/common';

// Collection of curated journaling prompts
const JOURNAL_PROMPTS = [
    "What are the most significant life lessons you’ve learned so far?",
    "What does success mean to you? Has your definition changed over time?",
    "Reflect on a time you failed. How did it shape your character or beliefs?",
    "Describe a moment of personal transformation in your life.",
    "What habits or routines have had the most significant impact on your personal growth?",
    "Who do you aspire to become in five years, and why?",
    "How do you typically respond to challenges, and what does this say about your resilience?",
    "What is your biggest fear? Where does it stem from, and how does it affect your life?",
    "If you could rewrite one chapter of your life, what would it be and why?",
    "What is the most important relationship in your life, and how has it shaped you?",
    "Reflect on a time you had to forgive someone. What did you learn about yourself and them?",
    "What is the biggest conflict you have ever had with someone you love?",
    "What qualities do you value most in a friend, and why?",
    "Do you think you are a good friend? Why?",
    "What are some old hurts you are still holding on to?",
    "Are there times you have felt like you could have been a better friend to someone?",
    "Describe a time when you felt truly understood by someone. What made it meaningful?",
    "What does family mean to you?",
    "What are some things you haven’t forgiven yourself for?",
    "How has your relationship with your family evolved?",
    "What does love mean to you, and how do you express it in your relationships?",
    "What boundaries are important for you in relationships, and how do you communicate them?",
    "Who has been a mentor or role model in your life, and what have you learned from them?",
    "Reflect on a friendship or relationship that ended. What lessons did you take from it?",
    "How do you typically handle stress?",
    "What are some things that trigger your negative emotions?",
    "Describe a time you felt overwhelming joy.",
    "How do you practice self-compassion, and how could you improve in this area?",
    "Reflect on the role gratitude plays in your daily life.",
    "What do you do to nurture your mental health, and how effective is it?",
    "Describe a time when you were your most vulnerable with someone.",
    "How do you cope with disappointment?",
    "What does happiness mean to you?",
    "What motivates you to get out of bed every morning?",
    "Do you believe you have a life’s purpose?",
    "If you could leave one lasting legacy, what would it be and why?",
    "What drives your passions, and how do they shape your life?",
    "Do you look for meaning in difficult or painful experiences?",
    "What role does faith or spirituality play in your life?",
    "What causes or issues matter most to you, and how do you contribute to them?",
    "Do you hope to make a difference in the world?",
    "How have your values evolved over time?",
    "What are your core beliefs, and how do they influence your decisions?",
    "How do you define yourself outside of your achievements or roles?",
    "Have your beliefs ever been challenged?",
    "How do you balance your individual identity with societal expectations?",
    "What parts of your identity bring you the most pride?",
    "What does personal freedom mean to you, and how do you pursue it?",
    "Write about a project or piece of work you’re most proud of.",
    "What role does art or creativity play in your life?",
    "How do you overcome creative blocks or doubts?",
    "Describe your dream creative project. Why is it important to you?",
    "What inspires your creative process?",
    "What moments from your childhood stand out most vividly?",
    "What are the key milestones in your life so far?",
    "What travel experience had a lasting impact on you?",
    "What does adventure mean to you, and how do you seek it in your life?",
    "How have your experiences with failure shaped your perspective on success?",
    "When was the last time you were courageous?",
    "How do you approach change, and what has it taught you about yourself?",
    "What’s a risk you took that paid off?",
    "How do you navigate uncertainty?",
    "Where do you see yourself in ten years?",
    "What goals have you set for yourself, and why are they important?",
    "What is your dream job?",
    "What skills or traits do you want to develop in the next year?",
    "How do you define personal fulfillment, and how do you plan to achieve it?",
    "What obstacles do you anticipate in achieving your goals? How will you overcome them?",
    "What is your biggest dream, and what’s holding you back from pursuing it?",
    "How do you want to grow emotionally, mentally, or spiritually in the future?",
    "What do you believe is the most pressing issue facing the world today?",
    "How do you contribute to your community, and what impact do you hope to have?",
    "How do your personal values align with societal norms?",
    "What changes would you like to see in the world, and how can you contribute to them?",
    "What social or political issue do you care deeply about? Why does it matter to you?",
    "What role does empathy play in how you interact with others and view the world?",
    "How do you stay hopeful in the face of global challenges?",
    "What are the most important lessons you’ve learned from a favourite book or film?",
    "What does 'home' mean to you, and how has your sense of home evolved?",
    "How do you celebrate your achievements?",
    "What are you grateful for today?",
    "What role does gratitude play in your relationships and daily life?",
    "How do you approach self-care?",
    "Reflect on the role of luck versus hard work in your life story.",
    "What does freedom mean to you, and how do you embody it in your choices?",
    "What are your unique strengths and talents?",
    "A dragon unexpectedly shows up in your backyard, seeking your help. What does it want, and why did it choose you?",
    "Write about a hidden world that only appears during a full moon.",
    "A wizard accidentally gives you their powers for a day. What do you do?",
    "In a world where everyone is born with a magical mark, yours suddenly changes. What does it mean?",
    "You discover an ancient spellbook, but every spell comes with a hidden price.",
    "Write about a kingdom where time flows backward.",
    "A cursed mirror reflects a different version of you every time you look into it.",
    "You are the last guardian of a magical forest that’s slowly losing its magic.",
    "A powerful artifact grants you the ability to rewrite one event in history. What do you change?",
    "You wake up in a world where mythical creatures rule, and humans are the rarity.",
    "Write about a society where people can trade their memories for magical abilities.",
    "A mysterious traveler claims to know your destiny. Do you believe them?",
    "You find an enchanted key that unlocks doors to other dimensions.",
    "The stars in the night sky begin disappearing one by one.",
    "You are the only one who can hear the whispers of an ancient, magical being.",
    "Write about a city where dreams manifest as physical entities.",
    "A forgotten prophecy reveals that you are the heir to a long-lost magical kingdom.",
    "In a world where everyone has a magical companion, yours is unlike anything anyone has ever seen.",
    "A library holds books that let you relive moments from history.",
    "You are given the power to control one element, but it comes with an unexpected twist.",
    "The Earth’s gravity mysteriously weakens for 24 hours. What happens?",
    "You discover a message from your future self, warning you about an impending disaster.",
    "A spaceship crash-lands in your neighborhood. What happens next?",
    "The government mandates that everyone upload their consciousness to a virtual world.",
    "Write about a world where robots have replaced all human jobs.",
    "A scientist accidentally creates a portal to an alternate reality.",
    "You are the first human to communicate with an alien species.",
    "In a world where memories can be traded, someone offers to sell you their happiest memory.",
    "Humanity discovers a planet identical to Earth, but it holds a dark secret.",
    "Write about a future where emotions are controlled by technology.",
    "A virus makes people capable of reading each other’s thoughts.",
    "You wake up to find that you’ve been cryogenically frozen for 200 years.",
    "A device allows you to relive your past lives.",
    "The moon suddenly breaks apart, causing chaos on Earth.",
    "In a world of holographic cities, you discover something that isn’t an illusion.",
    "A powerful AI begins to rewrite its programming, developing a mind of its own.",
    "You invent a machine that can stop time, but it malfunctions in a strange way.",
    "A colony on Mars uncovers evidence of an ancient alien civilization.",
    "Write about a world where people can live forever by transferring their consciousness into synthetic bodies.",
    "A satellite picks up a signal that turns out to be a distress call from another galaxy.",
    "You receive an anonymous letter claiming to know your darkest secret.",
    "A detective finds a photograph of themselves at a crime scene they’ve never been to.",
    "You inherit a house with a hidden room that hasn’t been opened in decades.",
    "Write about a town where everyone disappears overnight, leaving only cryptic clues.",
    "A stranger hands you an envelope and tells you to open it 'when the time is right.'",
    "A phone call from an unknown number tells you to leave your house immediately.",
    "Write about a character who finds a journal filled with entries about their life, written by someone else.",
    "A group of friends goes camping and wakes up to find one of them missing.",
    "You stumble upon a map that leads to a treasure with a dangerous secret.",
    "A small town experiences a series of inexplicable events every year on the same day.",
    "Your best friend starts acting strangely after a weekend trip.",
    "A stranger moves into your neighborhood, and strange things start happening.",
    "You wake up in a room with no memory of how you got there.",
    "Write about a detective who begins to suspect their partner of being involved in a crime.",
    "A child claims they can see events from the past in a mysterious old house.",
    "You find a message in a bottle that reveals a decades-old mystery.",
    "Write about a journalist uncovering a conspiracy that threatens their life.",
    "A security camera captures footage of something that shouldn’t be possible.",
    "You receive a package with no return address and no explanation.",
    "A person’s reflection in the mirror starts behaving differently from them.",
    "A family road trip takes an unexpected turn when a secret is revealed.",
    "Write about a character reconnecting with an estranged childhood friend.",
    "A random act of kindness changes the course of someone’s life.",
    "You overhear a conversation that changes how you view someone close to you.",
    "Write about a character struggling to let go of the past.",
    "A long-lost letter arrives, bringing unexpected news.",
    "A character meets their idol and is disappointed by the encounter.",
    "Write about a day that starts completely ordinary but ends life-changing.",
    "A character struggles to balance their dreams with their responsibilities.",
    "Write about someone confronting their fears in an unexpected way.",
    "A character inherits a family heirloom with an emotional history.",
    "Write about a reunion between two people who haven’t seen each other in decades.",
    "A character has a chance encounter with someone who changes their perspective on life.",
    "Write about a small-town tradition that brings the community together.",
    "A character makes an impulsive decision that leads to surprising consequences.",
    "Write about a parent and child navigating a strained relationship.",
    "A character moves to a new city and starts over completely.",
    "Write about a wedding where everything seems to go wrong.",
    "A character returns to their hometown after many years and faces their past.",
    "Write about a person discovering a hidden talent later in life.",
    "Write about a character who keeps seeing the same stranger everywhere they go.",
    "A dream feels so real that it starts to blur the lines between reality and imagination.",
    "Write about a character who finds a book that seems to be about their life.",
    "A sudden storm reveals something hidden beneath a city.",
    "Write about a character’s journey to find someone who has disappeared.",
    "A character receives an invitation to an event that changes their life.",
    "Write about a world where people can see the 'threads' connecting them to others.",
    "A family heirloom holds the secret to a long-lost treasure.",
    "Write about a town that celebrates a strange, unique holiday.",
    "A character wakes up one day with a completely new personality.",
    "Write about someone discovering a talent they never knew they had.",
    "A mysterious stranger offers to grant your character one wish.",
    "Write about a competition that has incredibly high stakes.",
    "A character writes letters to their future self, but someone else starts responding.",
    "Write about a road trip that doesn’t go as planned.",
    "A childhood keepsake holds a secret that changes a character’s life.",
    "Write about a character’s first day at a new school, job, or city.",
    "A character finds a photograph with a strange, unexplained detail in it.",
    "Write about a holiday dinner where a big family secret is revealed.",
    "A character finds a mysterious door that wasn’t there before."
  
] as const;

/**
 * Get a random journaling prompt
 */
export const getRandomPrompt = async (): Promise<string> => {
  // Simulate API call to maintain consistent behavior
  await delay(400);
  
  const randomIndex = Math.floor(Math.random() * JOURNAL_PROMPTS.length);
  return JOURNAL_PROMPTS[randomIndex];
};

/**
 * Get all available prompts
 */
export const getAllPrompts = async (): Promise<string[]> => {
  // Simulate API call to maintain consistent behavior
  await delay(600);
  
  return [...JOURNAL_PROMPTS];
};