import { delay } from '@/utils/common';

// Collection of curated journaling prompts
const JOURNAL_PROMPTS = [
    "What are the most significant life lessons you’ve learned so far?",
    "What does success mean to you? Has your definition changed over time?",
    "Reflect on a time you failed. How did it shape your character or beliefs?",
    "Describe a moment of personal transformation in your life.",
    "What habits or routines have had the most significant impact on your personal growth?",
    "Who do you aspire to become in five years, and why?",
    "How do you typically respond to challenges, and what does this say about your resilience?",
    "What is your biggest fear? Where does it stem from, and how does it affect your life?",
    "If you could rewrite one chapter of your life, what would it be and why?",
    "What is the most important relationship in your life, and how has it shaped you?",
    "Reflect on a time you had to forgive someone. What did you learn about yourself and them?",
    "What is the biggest conflict you have ever had with someone you love?",
    "What qualities do you value most in a friend, and why?",
    "Do you think you are a good friend? Why?",
    "What are some old hurts you are still holding on to?",
    "Are there times you have felt like you could have been a better friend to someone?",
    "Describe a time when you felt truly understood by someone. What made it meaningful?",
    "What does family mean to you?",
    "What are some things you haven’t forgiven yourself for?",
    "How has your relationship with your family evolved?",
    "What does love mean to you, and how do you express it in your relationships?",
    "What boundaries are important for you in relationships, and how do you communicate them?",
    "Who has been a mentor or role model in your life, and what have you learned from them?",
    "Reflect on a friendship or relationship that ended. What lessons did you take from it?",
    "How do you typically handle stress?",
    "What are some things that trigger your negative emotions?",
    "Describe a time you felt overwhelming joy.",
    "How do you practice self-compassion, and how could you improve in this area?",
    "Reflect on the role gratitude plays in your daily life.",
    "What do you do to nurture your mental health, and how effective is it?",
    "Describe a time when you were your most vulnerable with someone.",
    "How do you cope with disappointment?",
    "What does happiness mean to you?",
    "What motivates you to get out of bed every morning?",
    "Do you believe you have a life’s purpose?",
    "If you could leave one lasting legacy, what would it be and why?",
    "What drives your passions, and how do they shape your life?",
    "Do you look for meaning in difficult or painful experiences?",
    "What role does faith or spirituality play in your life?",
    "What causes or issues matter most to you, and how do you contribute to them?",
    "Do you hope to make a difference in the world?",
    "How have your values evolved over time?",
    "What are your core beliefs, and how do they influence your decisions?",
    "How do you define yourself outside of your achievements or roles?",
    "Have your beliefs ever been challenged?",
    "How do you balance your individual identity with societal expectations?",
    "What parts of your identity bring you the most pride?",
    "What does personal freedom mean to you, and how do you pursue it?",
    "Write about a project or piece of work you’re most proud of.",
    "What role does art or creativity play in your life?",
    "How do you overcome creative blocks or doubts?",
    "Describe your dream creative project. Why is it important to you?",
    "What inspires your creative process?",
    "What moments from your childhood stand out most vividly?",
    "What are the key milestones in your life so far?",
    "What travel experience had a lasting impact on you?",
    "What does adventure mean to you, and how do you seek it in your life?",
    "How have your experiences with failure shaped your perspective on success?",
    "When was the last time you were courageous?",
    "How do you approach change, and what has it taught you about yourself?",
    "What’s a risk you took that paid off?",
    "How do you navigate uncertainty?",
    "Where do you see yourself in ten years?",
    "What goals have you set for yourself, and why are they important?",
    "What is your dream job?",
    "What skills or traits do you want to develop in the next year?",
    "How do you define personal fulfillment, and how do you plan to achieve it?",
    "What obstacles do you anticipate in achieving your goals? How will you overcome them?",
    "What is your biggest dream, and what’s holding you back from pursuing it?",
    "How do you want to grow emotionally, mentally, or spiritually in the future?",
    "What do you believe is the most pressing issue facing the world today?",
    "How do you contribute to your community, and what impact do you hope to have?",
    "How do your personal values align with societal norms?",
    "What changes would you like to see in the world, and how can you contribute to them?",
    "What social or political issue do you care deeply about? Why does it matter to you?",
    "What role does empathy play in how you interact with others and view the world?",
    "How do you stay hopeful in the face of global challenges?",
    "What are the most important lessons you’ve learned from a favourite book or film?",
    "What does 'home' mean to you, and how has your sense of home evolved?",
    "How do you celebrate your achievements?",
    "What are you grateful for today?",
    "What role does gratitude play in your relationships and daily life?",
    "How do you approach self-care?",
    "Reflect on the role of luck versus hard work in your life story.",
    "What does freedom mean to you, and how do you embody it in your choices?",
    "What are your unique strengths and talents?",
    "A dragon unexpectedly shows up in your backyard, seeking your help. What does it want, and why did it choose you?",
    "Write about a hidden world that only appears during a full moon.",
    "A wizard accidentally gives you their powers for a day. What do you do?",
    "In a world where everyone is born with a magical mark, yours suddenly changes. What does it mean?",
    "You discover an ancient spellbook, but every spell comes with a hidden price.",
    "Write about a kingdom where time flows backward.",
    "A cursed mirror reflects a different version of you every time you look into it.",
    "You are the last guardian of a magical forest that’s slowly losing its magic.",
    "A powerful artifact grants you the ability to rewrite one event in history. What do you change?",
    "You wake up in a world where mythical creatures rule, and humans are the rarity.",
    "Write about a society where people can trade their memories for magical abilities.",
    "A mysterious traveler claims to know your destiny. Do you believe them?",
    "You find an enchanted key that unlocks doors to other dimensions.",
    "The stars in the night sky begin disappearing one by one.",
    "You are the only one who can hear the whispers of an ancient, magical being.",
    "Write about a city where dreams manifest as physical entities.",
    "A forgotten prophecy reveals that you are the heir to a long-lost magical kingdom.",
    "In a world where everyone has a magical companion, yours is unlike anything anyone has ever seen.",
    "A library holds books that let you relive moments from history.",
    "You are given the power to control one element, but it comes with an unexpected twist.",
    "The Earth’s gravity mysteriously weakens for 24 hours. What happens?",
    "You discover a message from your future self, warning you about an impending disaster.",
    "A spaceship crash-lands in your neighborhood. What happens next?",
    "The government mandates that everyone upload their consciousness to a virtual world.",
    "Write about a world where robots have replaced all human jobs.",
    "A scientist accidentally creates a portal to an alternate reality.",
    "You are the first human to communicate with an alien species.",
    "In a world where memories can be traded, someone offers to sell you their happiest memory.",
    "Humanity discovers a planet identical to Earth, but it holds a dark secret.",
    "Write about a future where emotions are controlled by technology.",
    "A virus makes people capable of reading each other’s thoughts.",
    "You wake up to find that you’ve been cryogenically frozen for 200 years.",
    "A device allows you to relive your past lives.",
    "The moon suddenly breaks apart, causing chaos on Earth.",
    "In a world of holographic cities, you discover something that isn’t an illusion.",
    "A powerful AI begins to rewrite its programming, developing a mind of its own.",
    "You invent a machine that can stop time, but it malfunctions in a strange way.",
    "A colony on Mars uncovers evidence of an ancient alien civilization.",
    "Write about a world where people can live forever by transferring their consciousness into synthetic bodies.",
    "A satellite picks up a signal that turns out to be a distress call from another galaxy.",
    "You receive an anonymous letter claiming to know your darkest secret.",
    "A detective finds a photograph of themselves at a crime scene they’ve never been to.",
    "You inherit a house with a hidden room that hasn’t been opened in decades.",
    "Write about a town where everyone disappears overnight, leaving only cryptic clues.",
    "A stranger hands you an envelope and tells you to open it 'when the time is right.'",
    "A phone call from an unknown number tells you to leave your house immediately.",
    "Write about a character who finds a journal filled with entries about their life, written by someone else.",
    "A group of friends goes camping and wakes up to find one of them missing.",
    "You stumble upon a map that leads to a treasure with a dangerous secret.",
    "A small town experiences a series of inexplicable events every year on the same day.",
    "Your best friend starts acting strangely after a weekend trip.",
    "A stranger moves into your neighborhood, and strange things start happening.",
    "You wake up in a room with no memory of how you got there.",
    "Write about a detective who begins to suspect their partner of being involved in a crime.",
    "A child claims they can see events from the past in a mysterious old house.",
    "You find a message in a bottle that reveals a decades-old mystery.",
    "Write about a journalist uncovering a conspiracy that threatens their life.",
    "A security camera captures footage of something that shouldn’t be possible.",
    "You receive a package with no return address and no explanation.",
    "A person’s reflection in the mirror starts behaving differently from them.",
    "A family road trip takes an unexpected turn when a secret is revealed.",
    "Write about a character reconnecting with an estranged childhood friend.",
    "A random act of kindness changes the course of someone’s life.",
    "You overhear a conversation that changes how you view someone close to you.",
    "Write about a character struggling to let go of the past.",
    "A long-lost letter arrives, bringing unexpected news.",
    "A character meets their idol and is disappointed by the encounter.",
    "Write about a day that starts completely ordinary but ends life-changing.",
    "A character struggles to balance their dreams with their responsibilities.",
    "Write about someone confronting their fears in an unexpected way.",
    "A character inherits a family heirloom with an emotional history.",
    "Write about a reunion between two people who haven’t seen each other in decades.",
    "A character has a chance encounter with someone who changes their perspective on life.",
    "Write about a small-town tradition that brings the community together.",
    "A character makes an impulsive decision that leads to surprising consequences.",
    "Write about a parent and child navigating a strained relationship.",
    "A character moves to a new city and starts over completely.",
    "Write about a wedding where everything seems to go wrong.",
    "A character returns to their hometown after many years and faces their past.",
    "Write about a person discovering a hidden talent later in life.",
    "Write about a character who keeps seeing the same stranger everywhere they go.",
    "A dream feels so real that it starts to blur the lines between reality and imagination.",
    "Write about a character who finds a book that seems to be about their life.",
    "A sudden storm reveals something hidden beneath a city.",
    "Write about a character’s journey to find someone who has disappeared.",
    "A character receives an invitation to an event that changes their life.",
    "Write about a world where people can see the 'threads' connecting them to others.",
    "A family heirloom holds the secret to a long-lost treasure.",
    "Write about a town that celebrates a strange, unique holiday.",
    "A character wakes up one day with a completely new personality.",
    "Write about someone discovering a talent they never knew they had.",
    "A mysterious stranger offers to grant your character one wish.",
    "Write about a competition that has incredibly high stakes.",
    "A character writes letters to their future self, but someone else starts responding.",
    "Write about a road trip that doesn’t go as planned.",
    "A childhood keepsake holds a secret that changes a character’s life.",
    "Write about a character’s first day at a new school, job, or city.",
    "A character finds a photograph with a strange, unexplained detail in it.",
    "Write about a holiday dinner where a big family secret is revealed.",
    "A character finds a mysterious door that wasn’t there before.",
    
  "Write a letter to your future self 10 years from now.",
  "Write a letter to your inner child.",
  "Write a letter apologizing to yourself for something you regret.",
  "Write a letter celebrating your greatest achievement so far.",
  "Write a letter to yourself about a fear you want to overcome.",
  "Write a letter to yourself as if you were your best friend.",
  "Write a letter forgiving yourself for a mistake.",
  "Write a letter to yourself from 10 years ago.",
  "Write a letter encouraging yourself to take a leap of faith.",
  "Write a letter to your future self reminding them of what’s important right now.",
  "Write a letter reflecting on your personal growth over the last year.",
  "Write a letter to yourself as if you were your biggest critic.",
  "Write a letter to younger self about a goal you've achieved.",
  "Write a letter to your past self explaining something you’ve learned the hard way.",
  "Write a letter to yourself about the things you love about who you are.",
  "Write a letter to your future self sharing your wildest dreams.",
  "Write a letter to your parents about something you’ve never told them.",
  "Write a letter to a sibling, expressing gratitude or resolving a conflict.",
  "Write a letter to a grandparent about what you admire most about them.",
  "Write a letter to a family member who has passed away.",
  "Write a letter to a family member you’ve lost touch with.",
  "Write a letter to your child, whether real or imagined, about your hopes for them.",
  "Write a letter to your parents explaining how they shaped who you are today.",
  "Write a letter to an ancestor about what your life is like now.",
  "Write a letter to a family member apologizing for something.",
  "Write a letter to a family member thanking them for their support.",
  "Write a letter to a younger family member, giving them advice about life.",
  "Write a letter to a family member sharing a cherished memory with them.",
  "Write a letter to a family member about a lesson they unknowingly taught you.",
  "Write a letter to your family as a whole.",
  "Write a letter to your future grandchildren about your life today.",
  "Write a letter to a family member who has been distant, asking to reconnect.",
  "Write a letter to a family member about a difficult but necessary topic.",
  "Write a letter to your parents telling them about something they don’t know about you.",
  "Write a letter to your childhood best friend about a memory you’ll never forget.",
  "Write a letter to your closest friend, thanking them for their presence in your life.",
  "Write a letter to a friend you’ve lost touch with, sharing how much you miss them.",
  "Write a letter to a friend apologizing for something you did.",
  "Write a letter to a friend you’ve drifted apart from, wondering what went wrong.",
  "Write a letter to a friend who inspired you.",
  "Write a letter to a new friend about how they’ve changed your life.",
  "Write a letter to a friend who helped you through a tough time.",
  "Write a letter to your best friend about a secret you’ve never shared.",
  "Write a letter to a friend explaining how much they mean to you.",
  "Write a letter to a friend you admire, telling them why they inspire you.",
  "Write a letter to a friend about a funny memory you both share.",
  "Write a letter to a friend who moved away.",
  "Write a letter to a friend who taught you an important life lesson.",
  "Write a letter to a friend about your dreams for the future.",
  "Write a letter to a friend who always makes you laugh.",
  "Write a letter to a friend describing a day you’ll never forget with them.",
  "Write a letter to a friend explaining why you value their friendship.",
  "Write a letter to a stranger who changed your life in a small way.",
  "Write a letter to the person who found your lost wallet.",
  "Write a letter to someone who inspired you from afar.",
  "Write a letter to the next person who will live in your home.",
  "Write a letter to a stranger you pass by every day.",
  "Write a letter to the person who made your favorite book, movie, or song.",
  "Write a letter to someone you’ll never meet but would like to.",
  "Write a letter to the person who invented something you love.",
  "Write a letter to a stranger who changed history.",
  "Write a letter to someone sitting alone in a café.",
  "Write a letter to a stranger who helped you without realizing it.",
  "Write a letter to the next generation about the world today.",
  "Write a letter to a stranger from 100 years in the future.",
  "Write a letter to someone from 100 years in the past.",
  "Write a letter to someone you saw but never met, imagining their story.",
  "Write a letter to the person who created your favorite place.",
  "Write a letter to the future owner of a cherished item you’ll pass down.",
  "Write a letter to happiness, asking what it takes to find it.",
  "Write a letter to fear, asking it why it exists.",
  "Write a letter to love, thanking it for all it has taught you.",
  "Write a letter to time, asking it to slow down or speed up.",
  "Write a letter to your dreams, wondering why they sometimes feel so real.",
  "Write a letter to hope, asking it to stay by your side.",
  "Write a letter to grief, asking it to be gentler.",
  "Write a letter to courage, thanking it for showing up when you needed it most.",
  "Write a letter to regret, asking it to stop haunting you.",
  "Write a letter to failure, thanking it for the lessons it taught you.",
  "Write a letter to peace, asking it to find you and the world.",
  "Write a letter to doubt, confronting how it holds you back.",
  "Write a letter to success, asking it to explain its true meaning.",
  "Write a letter to forgiveness, exploring what it means to you.",
  "Write a letter to your future, wondering what it has in store for you.",
  "Write a letter to your past, reconciling with mistakes and growth.",
  "Write a letter to passion, celebrating its impact on your life.",
  "Write a letter to wisdom, asking it to guide you.",
  "Write a letter to freedom, exploring what it means to you.",
  "Write a letter to yourself about the most important thing you’ve learned so far.",
  "What is a truth about yourself you avoid admitting to others?",
  "What is your most irrational fear, and where do you think it comes from?",
  "What’s something you’ve done that you deeply regret but have never spoken about?",
  "Write about a time you hurt someone you loved.",
  "What’s a secret you’ve kept for a long time, and why?",
  "What’s the most shameful thought you’ve ever had?",
  "What do you dislike most about yourself, and why is it so hard to change?",
  "Write about a moment when you realized you were wrong but couldn’t admit it.",
  "What’s a habit or behavior you know is toxic, but you can’t let go of?",
  "If you could erase one memory from your life, what would it be and why?",
  "What’s a lie you’ve told that still haunts you?",
  "When was the last time you let fear hold you back from something important?",
  "Write about a time when you acted out of jealousy.",
  "What’s the most selfish thing you’ve ever done?",
  "When was the last time you felt completely out of control?",
  "What’s a part of your past that you’re afraid to revisit?",
  "What is the hardest lesson you’ve had to learn about yourself?",
  "What’s something you’ve never forgiven yourself for?",
  "Write about a time you let someone down and never made it right.",
  "What’s a belief you hold that others would find controversial?",
  "Write about the most toxic relationship you’ve ever been in.",
  "When was the last time you truly felt abandoned?",
  "What’s a boundary you’ve failed to set with someone, and how has it hurt you?",
  "Write about a time when you were the toxic person in a relationship.",
  "What’s a friendship you’ve lost that still stings?",
  "When was the last time you used someone for your own gain?",
  "What’s a time you stayed in a relationship longer than you should have?",
  "What’s something you’ve never told your parents, and why?",
  "Write about a time you let a loved one walk away without fighting for them.",
  "What’s something you wish you could say to someone but never will?",
  "Write about a time you felt deeply unloved.",
  "What’s the biggest grudge you’re still holding, and why?",
  "What’s a time you betrayed someone’s trust?",
  "What’s the hardest apology you’ve ever had to give?",
  "Write about a moment when you realized you didn’t truly know someone you loved.",
  "When was the last time you felt completely unworthy of love?",
  "What’s something you’ve never forgiven someone else for?",
  "Write about a time when you hurt someone unintentionally.",
  "What’s the most manipulative thing you’ve ever done?",
  "Write about a time you made someone cry and didn’t apologize.",
  "What’s a stereotype you’ve believed about others, and how did it affect your actions?",
  "Write about a moment when you failed to stand up for what was right.",
  "What’s a societal norm you secretly agree with but feel guilty about?",
  "When was the last time you judged someone unfairly?",
  "What’s a prejudice you were raised with that you still struggle to unlearn?",
  "Write about a time you witnessed an injustice and did nothing.",
  "What’s a belief you have that conflicts with your values?",
  "Write about a time you benefited from privilege but ignored it.",
  "When have you been silent when someone needed your voice?",
  "Write about a time you felt complicit in something wrong.",
  "What’s a time you prioritized yourself over someone in need?",
  "Write about a time you questioned your own morals.",
  "What’s an opinion you hold that would alienate you from your community?",
  "When have you followed a crowd even though you disagreed?",
  "What’s a cause you believe in but haven’t supported with action?",
  "Write about a time you knowingly participated in something unethical.",
  "What’s the most hypocritical thing you’ve ever done?",
  "Write about a moment when you felt disconnected from humanity.",
  "What’s a time you let prejudice guide your actions?",
  "Write about a time you justified something you knew was wrong.",
  "What’s a fear you’ve never shared with anyone?",
  "Write about the last time you cried.",
  "What’s the hardest decision you’ve ever had to make?",
  "When was the last time you felt completely powerless?",
  "Write about a dream that scared you because it felt too real.",
  "What’s a failure that still haunts you?",
  "Write about a time you felt deeply humiliated.",
  "What’s something you’re afraid to admit to yourself?",
  "When was the last time you felt completely alone?",
  "Write about a moment when you doubted your own sanity.",
  "What’s a fear you have about the future?",
  "Write about a moment when your vulnerability was taken advantage of.",
  "What’s the most terrifying 'what if' you’ve ever considered?",
  "Write about a time you questioned your purpose in life.",
  "What’s something you’ve avoided doing because you’re afraid of failure?",
  "Write about a moment when you felt completely exposed.",
  "Write about a time you felt unsafe but didn’t know what to do.",
  "What’s a fear you’ve had since childhood that still lingers?",
  "Write about a moment when your greatest fear almost came true.",
  "Write about a time when you resisted change and how it affected you.",
  "What’s a dream you’ve given up on, and why?",
  "Write about a time you outgrew someone or something important to you.",
  "What’s a part of yourself you’ve had to leave behind to grow?",
  "Write about a time when you were forced to face an uncomfortable truth.",
  "What’s the hardest goodbye you’ve ever had to say?",
  "Write about a moment when you realized you were no longer the person you used to be.",
  "What’s a time you embraced a change you were terrified of?",
  "Write about a time you were forced to let go of control.",
  "What’s a lesson you’ve learned that came with a heavy cost?",
  "Write about a time you failed to adapt to a new situation.",
  "What’s a risk you regret not taking?",
  "Write about a moment when growth felt painful but necessary.",
  "What’s something you’ve lost that you can never replace?",
  "Write about a time when your identity was challenged.",
  "What’s a change you need to make but are afraid to start?",
  "Write about a time you had to rebuild yourself from scratch.",
  "What’s a moment when you felt like giving up but didn’t?",
  "Write about the hardest choice you’ve made in pursuit of growth.",
  "What’s something you wish you could unlearn, and why?"
  
] as const;

/**
 * Get a random journaling prompt
 */
export const getRandomPrompt = async (): Promise<string> => {
  // Simulate API call to maintain consistent behavior
  await delay(400);
  
  const randomIndex = Math.floor(Math.random() * JOURNAL_PROMPTS.length);
  return JOURNAL_PROMPTS[randomIndex];
};

/**
 * Get all available prompts
 */
export const getAllPrompts = async (): Promise<string[]> => {
  // Simulate API call to maintain consistent behavior
  await delay(600);
  
  return [...JOURNAL_PROMPTS];
};